chemapp/urls.py
from django.urls import path
from chemapp import views
from django.contrib import admin
from django.conf.urls import url

admin.autodiscover()
admin.site.enable_nav_sidebar = False

app_name = 'chemapp'

urlpatterns = [
    path('', views.user_login, name='login'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('logout/', views.user_logout, name='logout'),

    # Degree URLs
    path('degrees/', views.degrees, name='degrees'),
    path('degrees/add_degree/', views.add_degree, name='add_degree'),
    path('degrees/upload_degree_csv/', views.upload_degree_csv, name='upload_degree_csv'),
    path('degrees/<slug:degree_code_slug>/edit_degree', views.edit_degree, name='edit_degree'),
    path('degrees/<slug:degree_code_slug>/delete_degree', views.delete_degree, name='delete_degree'),

    # Course URLs
    path('courses/', views.courses, name='courses'),
    path('courses/add_course/',views.add_course, name='add_course'),
    path('courses/upload_course_csv/', views.upload_course_csv, name='upload_course_csv'),
    path('courses/<slug:course_name_slug>/', views.course, name='course'),
    path('courses/<slug:course_name_slug>/edit_course/', views.edit_course, name='edit_course'),
    path('courses/<slug:course_name_slug>/delete_course/', views.delete_course, name='delete_course'),
    path('courses/<slug:course_name_slug>/upload_student_csv/', views.upload_student_csv, name='upload_student_csv'),
	path('courses/<slug:course_name_slug>/students/', views.course_students, name='course_students'),

    # Export URLs
    path('courses/<slug:course_name_slug>/export_course_grades/',views.export_course_grades, name='export_course_grades'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/export_assessment_grades',views.export_assessment_grades, name='export_assessment_grades'),

    # Assessment URLs
    path('courses/<slug:course_name_slug>/add_assessments/', views.add_assessments, name='add_assessments'),
    path('courses/<slug:course_name_slug>/upload_assessment_csv/', views.upload_assessment_csv, name='upload_assessment_csv'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/map/', views.map, name='map'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/map/upload_map_csv/', views.upload_map_csv, name='upload_map_csv'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/edit_assessment/', views.edit_assessment, name='edit_assessment'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/delete_assessment/', views.delete_assessment, name='delete_assessment'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/upload_student_assessment_info_csv/', views.upload_student_assessment_info_csv, name='upload_student_assessment_info_csv'),



    # Assessment Component URLs
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/add_assessmentComponents/', views.add_assessmentComponents, name='add_assessmentComponents'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/upload_assessment_comp_csv/', views.upload_assessment_comp_csv, name='upload_assessment_comp_csv'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/<slug:assessment_component_slug>/edit_component/', views.edit_assessmentComponent, name='edit_assessmentComponent'),
    path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/<slug:assessment_component_slug>/delete_component/', views.delete_assessmentComponent, name='delete_assessmentComponent'),
 	path('courses/<slug:course_name_slug>/<slug:assessment_name_slug>/<slug:assessment_component_slug>/upload_grades_csv/', views.upload_grades_csv, name='upload_grades_csv'),

    # Student URLs
    path('students/add_student/', views.add_student, name='add_student'),
    path('students/<student_id>/', views.student, name='student'),
    path('students/<student_id>/edit_student/', views.edit_student, name='edit_student'),
    path('students/<student_id>/delete_student/', views.delete_student, name='delete_student'),

    # Student Grades URLs
    path('students/<student_id>/<slug:course_name_slug>/<slug:assessment_name_slug>/add_grades/', views.add_grades, name='add_grades'),
    path('students/<student_id>/<slug:course_name_slug>/<slug:assessment_name_slug>/edit_grades/', views.edit_grades, name='edit_grades'),
    path('students/<student_id>/<slug:course_name_slug>/<slug:assessment_name_slug>/delete_grades/', views.delete_grades, name='delete_grades'),
    path('students/<student_id>/<slug:course_name_slug>/<slug:assessment_name_slug>/add_final_grade/', views.add_final_grade, name='add_final_grade'),
    path('students/<student_id>/<slug:course_name_slug>/<slug:assessment_name_slug>/edit_final_grade/', views.edit_final_grade, name='edit_final_grade'),
    path('students/<student_id>/<slug:course_name_slug>/<slug:assessment_name_slug>/delete_final_grade/', views.delete_final_grade, name='delete_final_grade'),

    # Staff URLs
    path('staff/', views.staff, name='staff'),
    path('staff/add_staff/', views.add_staff, name='add_staff'),
    path('staff/<staffID>/', views.staff_member, name='staff_member'),
    path('staff/<staffID>/edit_staff/', views.edit_staff, name='edit_staff'),
    path('staff/<staffID>/delete_staff/', views.delete_staff, name='delete_staff'),

    # Search URLs
    path('search/', views.search_site, name='search_site'),

    # Ajax URLs
    path('ajax/filter-courses/', views.ajax_filter_courses, name='ajax_filter_courses'),
]

cs35_site_project/urls.py
from django.contrib import admin
from django.urls import path, include
from chemapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.user_login, name='login'),
    path('chemapp/', include('chemapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chemapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from chemapp.models import *
from chemapp.forms import *
import csv, io
from django.forms.formsets import formset_factory
from django.template.defaultfilters import slugify
from django.db.models import Q
import random
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from chemapp.utils import user_edit_perm_check, permission_required_context, user_upload_grades_perm_check
from django.contrib.auth.decorators import permission_required
from datetime import datetime
import pytz
from decimal import *
from .admin import CourseGrade
import json

GRADE_TO_BAND = {22: 'A1', 21: 'A2', 20: 'A3', 19: 'A4', 18: 'A5',
                 17: 'B1', 16: 'B2', 15: 'B3',
                 14: 'C1', 13: 'C2', 12: 'C3',
                 11: 'D1', 10: 'D2', 9: 'D3',
                 8: 'E1', 7: 'E2', 6: 'E3',
                 5: 'F1', 4: 'F2', 3: 'F3',
                 2: 'G1', 1: 'G2', 0: 'H',
                 }


def addCoursePermissions(course_slug):
    course_slug = course_slug.upper()
    content_type = ContentType.objects.get_for_model(Course)
    Permission.objects.create(codename='can_edit_course' + course_slug, name="can edit course " + course_slug,
                              content_type=content_type, )
    Permission.objects.create(codename='can_upload_grades_for' + course_slug,
                              name="can upload grades for " + course_slug, content_type=content_type, )
    return


def removeCoursePermissions(course_slug):
    course_slug = course_slug.upper()
    content_type = ContentType.objects.get_for_model(Course)
    Permission.objects.filter(codename='can_edit_course' + course_slug, name="can edit course " + course_slug,
                              content_type=content_type, ).delete()
    Permission.objects.filter(codename='can_upload_grades_for' + course_slug,
                              name="can upload grades for " + course_slug, content_type=content_type, ).delete()
    return


@login_required
def home(request):
    context_dict = {'boldmessage': 'Home'}
    return render(request, 'chemapp/home.html', context=context_dict)


@login_required
def about(request):
    context_dict = {'boldmessage': 'About'}
    return render(request, 'chemapp/about.html', context=context_dict)


@login_required
def degrees(request):
    degreesDict = {}

    degrees = Degree.objects.all()
    degreesDict['degrees'] = degrees

    return render(request, 'chemapp/degrees.html', context=degreesDict)


@login_required
@permission_required_context('chemapp.add_degree', 'No permission to add_degree', raise_exception=True)
def add_degree(request):
    addDegreeDict = {}

    DegreeFormSet = formset_factory(DegreeForm, extra=1)

    if (request.method == 'POST'):
        degree_formset = DegreeFormSet(request.POST)

        if degree_formset.is_valid():
            degrees = []

            # This is used to check for Degree duplicates
            codes = []
            for form in degree_formset:
                degreeCode = form.cleaned_data.get('degreeCode').upper()
                name = form.cleaned_data.get('name')
                slug = slugify(degreeCode)

                # Check if Degree already exists
                try:
                    degree = Degree.objects.get(degreeCode=degreeCode)
                    messages.error(request, "Degree with code: " + degreeCode + " already exists!")
                    return redirect(reverse('chemapp:add_degree'))
                except Degree.DoesNotExist:
                    pass

                if degreeCode in codes:
                    messages.error(request, "Duplicate degree " + degreeCode + " was only added once!")
                else:
                    codes.append(degreeCode)
                    degrees.append(Degree(degreeCode=degreeCode,
                                          name=name,
                                          slug=slug,
                                          numberOfCourses=0,
                                          numberOfStudents=0))

            Degree.objects.bulk_create(degrees)

            messages.success(request, "Degrees Added Successfully!")
            return redirect(reverse('chemapp:degrees'))
        else:
            print(degree_formset.errors)

    else:
        degree_formset = DegreeFormSet()

    addDegreeDict['degree_formset'] = degree_formset

    return render(request, 'chemapp/add_degree.html', context=addDegreeDict)


@login_required
@permission_required_context('chemapp.change_degree', 'No permission to edit_degree', raise_exception=True)
def edit_degree(request, degree_code_slug):
    degree = Degree.objects.get(slug=degree_code_slug)

    editDegreeDict = {}
    editDegreeDict['degree_code_slug'] = degree_code_slug
    editDegreeDict['degree'] = degree

    if (request.method == 'POST'):
        edit_degree_form = EditDegreeForm(request.POST)

        if edit_degree_form.is_valid():
            name = edit_degree_form.cleaned_data.get('name')

            degree.name = name

            degree.save()

            messages.success(request, 'Degree was updated successfully!')
            return redirect(reverse('chemapp:degrees'))
        else:
            print(edit_degree_form.errors)
    else:
        edit_degree_form = EditDegreeForm(instance=degree)

    editDegreeDict['edit_degree_form'] = edit_degree_form

    return render(request, 'chemapp/edit_degree.html', context=editDegreeDict)


@login_required
@permission_required_context('chemapp.delete_degree', 'No permission to delete_degree', raise_exception=True)
def delete_degree(request, degree_code_slug):
    delDegree = Degree.objects.get(slug=degree_code_slug)

    if request.method == 'POST':
        courses = Course.objects.filter(degree=delDegree)

        for course in courses:
            removeCoursePermissions(course.slug)

        delDegree.delete()

        messages.success(request, 'Degree deleted successfully!')
        return redirect(reverse('chemapp:degrees'))

    return render(request, 'chemapp/degrees.html', context={})


@login_required
@permission_required_context('chemapp.add_degree', 'No permission to add_degree', raise_exception=True)
def upload_degree_csv(request):
    if request.method == "GET":
        return render(request, 'chemapp/upload_degree_csv.html')

    csv_file = request.FILES['file']
    if not csv_file.name.endswith('.csv'):
        messages.error(request, 'THIS IS NOT A CSV FILE')
        return redirect(reverse('chemapp:degrees'))

    data_set = csv_file.read().decode('UTF-8')
    io_string = io.StringIO(data_set)
    next(io_string)
    for column in csv.reader(io_string, delimiter=',', quotechar="|"):
        created = Degree.objects.update_or_create(
            degreeCode=column[0],
            defaults={'name': column[1],
                      }
        )

    messages.success(request, "Degrees Added Successfully!")
    return redirect(reverse('chemapp:degrees'))


@login_required
def courses(request):
    coursesDict = {}
    courses = Course.objects.all()

    levelDict = {}

    for course in courses:
        slug = course.slug
        code = course.code
        color = course.courseColor
        level = course.level
        name = course.name

        if level not in levelDict.values():
            levelDict[level] = level

        courseList = [level, slug, code, color, name]

        coursesDict[course] = courseList

    return render(request, 'chemapp/courses.html', {'courses': coursesDict, 'levels': levelDict})


# Dictionary structure
# courseDict = {'course':courseObject,
#               'assessments':{assessmentObject1:[componentObject1,componentObject2],
#                              assessmentObject2:[componentObject3,componentObject4]},
#              }
@login_required
def course(request, course_name_slug):
    courseDict = {}
    courseDict['course_name_slug'] = course_name_slug

    try:
        course = Course.objects.get(slug=course_name_slug)
        assessments = Assessment.objects.filter(course=course)
        courseDict['course'] = course
        courseDict['assessments'] = {}

        for assessment in assessments:
            courseDict['assessments'][assessment] = []
            components = AssessmentComponent.objects.filter(assessment=assessment)

            for component in components:
                courseDict['assessments'][assessment].append(component)

    except Course.DoesNotExist:
        raise Http404("Course does not exist")

    return render(request, 'chemapp/course.html', context=courseDict)


@login_required
def export_course_grades(request, course_name_slug):
    course = Course.objects.get(slug=course_name_slug)
    students = Student.objects.filter(courses=course)

    response = HttpResponse(content_type='text/csv')
    # Bug will occur in 79 years :)
    academicYear = '20' + course.academicYearTaught[:2]
    filename = course.code + '_' + academicYear
    response['Content-Disposition'] = 'attachment; filename=' + '"' + filename + '.csv"'

    writer = csv.writer(response)
    writer.writerow(['Course', 'Degree', 'AcademicYear', 'ANONID', 'EMPLID', 'Name', 'Grade'])
    for student in students:
        studentName = student.firstName + ',' + student.lastName
        try:
            courseGrade = CourseGrade.objects.get(course=course, student=student)
            band = courseGrade.band
        except CourseGrade.DoesNotExist:
            band = 'NA'

        writer.writerow([course.code, course.degree, course.academicYearTaught, student.anonID,
                         student.studentID, studentName, band])

    return response


@login_required

templates/chemapp/add_assessments.html
{% extends 'chemapp/base.html' %}
{% load static %}

{% block js_block %}
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/chemapp-addRemoveAssessmentForm.js' %}"></script>
{% endblock %}

{% block title_block %}
Add Assessments
{% endblock %}

{% block body_block %}
<div class="container mb-5 ">
  <h2> Add Assessments </h2>
  {% if existingAssessments %}
  <h4> Existing Assessments</h4>
  {% for assessment in existingAssessments %}
  <p> {{ assessment.assessmentName }} with {{ assessment.weight }} weight </p>
  {% endfor %}
  {% endif %}
  <form id="add_assessment_form" method="post" action="{% url 'chemapp:add_assessments' course_name_slug=course_name_slug %}" enctype="multipart/form-data">
    {% csrf_token %}

    {{ assessment_formset.management_form }}
    {% for assessment_form in assessment_formset %}
    <div class="assessment-formset row">
      {% for field in assessment_form %}
      <div class="col ">
        <div class="form-floating">
          {{ field }}
          <label for="floating{{ field.label }}">{{ field.label }}</label>
        </div>
        <div class=" text-start">
          <div id="" class="form-text ps-2">{{ field.help_text }}</div>
        </div>
        {% for error in field.errors %}
        <div class="text-danger">
          <strong>*{{ error|escape }}</strong>
        </div>
        {% endfor %}
        <br>
      </div>
      {% endfor %}
    </div>
    {% endfor %}
    <br>
    <button class="btn btn-primary mt-5" type="submit">Save</button>
  </form>
</div>

{% endblock %}

templates/chemapp/add_student.html
{% extends 'chemapp/base.html' %}
{% load static %}



{% block js_block %}
<script src="{% static 'js/chemapp-filterCoursesAddStudentPage.js' %}"></script>
<script src="{% static 'js/chemapp-selectCoursesOverride.js' %}"></script>
<script src="{% static 'js/chemapp-studentInputMask.js' %}"></script>
{% endblock %}

{% block title_block %}
Add student
{% endblock %}

{% block body_block %}
<div class="container ">
  <div>
    <h2 class="mb-4"> Add a Student </h2>

    <form id="add_student_form" method="post" filter_courses_url = "{% url 'chemapp:ajax_filter_courses' %}" action="{% url 'chemapp:add_student' %}" enctype="multipart/form-data">

      {% csrf_token %}


      <div class="row ">
        {% for field in student_form %}

        {% if field.label == 'First Name' %}
        <div class="col-4 mb-4">
          {% elif field.label == 'Last Name' %}
          <div class="col-4">
            {% elif field.label == 'Gap Year' %}
            <div class="col-8 my-3 ">
              {% elif field.label == 'StudentID' %}
              <div class="col-4 mb-4">
                {% elif field.label == 'Comments' %}
                <div class="col-8">

                  {% else %}
                  <div class="col-12 mb-4">
                    {% endif %}



                    {% if field.label == 'Gap Year' %}

                    <div class="form-check ">
                      {{ field }}
                      <label class="form-check-label" for="flexCheckDefault">{{ field.label }}</label>
                    </div>

                    {% else %}




                    <div class="form-floating">
                      {{ field }}
                      <label for="floating{{ field.label }}">{{ field.label }}</label>
                    </div>
                    {% endif %}

                    <div class=" text-start">
                      <div id="" class="form-text ps-2">{{ field.help_text }}</div>
                    </div>



                    {% for error in field.errors %}
                    <div class="text-danger">
                      <strong>*{{ error|escape }}</strong>
                    </div>
                    {% endfor %}
                  </div>


                  {% endfor %}


                  {% for error in form.non_field_errors %}
                  <div class="">
                    <strong>*{{ error|escape }}</strong>
                  </div>
                  {% endfor %}


                </div>

                <button class="btn btn-primary mt-5" type="submit">Save</button>
              </form>

            </div>
          </div>

          {% endblock %}

templates/chemapp/course_students.html
{% extends 'chemapp/base.html' %}


{% block title_block %}
Students
{% endblock %}


{% block body_block %}



<div class="container ">
  <h2>{{course_code}} | Students</h2>
  {% if students %}
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Student ID</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col" class="text-end">Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
      <tr>
        <th scope="row">{{ student.studentID }}</th>
        <td>{{student.firstName}}</td>
        <td>{{student.lastName}}</td>
        <td>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <a class="btn btn-info"href="{% url 'chemapp:student' student_id=student.studentID %}">View</a>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <h4>There are no Students for this course</h4>
  {% endif %}

  <div class=" mb-3 mt-3 d-grid gap-2 d-md-flex justify-content-md-start">
    <a class="btn btn-success " href="{% url 'chemapp:add_student' %}"><i class="bi bi-plus"></i> Add a student</a>
    <a class="btn btn-primary " href="{% url 'chemapp:upload_student_csv' course_name_slug=course_name_slug %}"><i class="pe-1 bi bi-file-earmark-arrow-up"></i> Upload CSV File to add students to this course</a>
  </div>
</div>
{% endblock %}

templates/chemapp/edit_assessment.html
{% extends 'chemapp/base.html' %}
{% load static %}

{% block title_block %}
Edit Assessment
{% endblock %}

{% block body_block %}
<div class="container mb-5 ">
    <h2> Edit Assessment "{{assessment.assessmentName}}" </h2>

    <form id="edit_assessment_form" method="post" action="{% url 'chemapp:edit_assessment' course_name_slug=course_name_slug assessment_name_slug=assessment_name_slug %}"  enctype="multipart/form-data">

        {% csrf_token %}

        {{ edit_assessment_form.as_p }}

        <button type="submit" class="btn btn-primary mt-5">Save</button>
    </form>
</div>

{% endblock %}

templates/chemapp/edit_component.html
{% extends 'chemapp/base.html' %}
{% load static %}

{% block title_block %}
Edit Component
{% endblock %}

{% block body_block %}
<div class="container mb-5 ">
    <h2> Edit Component "{{ component.description }}" </h2>

    <form id="edit_component_form" method="post" action="{% url 'chemapp:edit_assessmentComponent' course_name_slug=course_name_slug assessment_name_slug=assessment_name_slug assessment_component_slug=assessment_component_slug %}"  enctype="multipart/form-data">

        {% csrf_token %}

        {{ edit_component_form.as_p }}

        <button type="submit" class="btn btn-primary mt-5">Save</button>
    </form>
</div>

{% endblock %}

templates/chemapp/edit_course.html
{% extends 'chemapp/base.html' %}
{% load static %}

{% block js_block %}
<script src="{% static 'js/chemapp-courseInputMask.js' %}"></script>
<script src="{% static 'js/chemapp-selectLecturersOverride.js' %}"></script>
{% endblock %}

{% block title_block %}
Edit a Course
{% endblock %}

{% block body_block %}
<div class="container mb-5 ">
  <h2> Edit Course </h2>

  <form id="edit_course_form" method="post" action="{% url 'chemapp:edit_course' course_name_slug=course_name_slug %}" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="row ">
      {% for field in edit_course_form %}

      {% if field.label == 'Description'  %}
      <div class="col-8 mb-2">
        {% elif field.label == 'Comments' %}
        <div class="col-8">
          {% elif field.label == 'Color' %}
          <div class="col-12">
            {% else %}
            <div class="col-12 mb-4">
              {% endif %}

              {% if field.label == 'Color' %}
              <label for="exampleColorInput" class="form-label mt-2">Color picker</label>

              {{ field }}

              {% else %}




              <div class="form-floating">
                {{ field }}
                <label for="floating{{ field.label }}">{{ field.label }}</label>
              </div>
              {% endif %}

              <div class=" text-start">
                <div id="" class=" ps-2 form-text">{{ field.help_text }}</div>
              </div>



              {% for error in field.errors %}
              <div class="text-danger">
                <strong>*{{ error|escape }}</strong>
              </div>
              {% endfor %}
            </div>


            {% endfor %}


            {% for error in form.non_field_errors %}
            <div class="">
              <strong>*{{ error|escape }}</strong>
            </div>
            {% endfor %}


          </div>


          <button type="submit" class="btn btn-primary mt-5">Save</button>
        </form>
      </div>

      {% endblock %}

templates/chemapp/edit_grades.html
{% extends 'chemapp/base.html' %}
{% load static %}

{% block title_block %}
Edit Grades
{% endblock %}

{% block body_block %}
<div class="container mb-5 ">
  <h2> Edit Grades</h2>

  <h2> {{ assessment.assessmentName }} </h2>

  <form id="add_grade_form" method="post" action="{% url 'chemapp:edit_grades' student_id=student_id course_name_slug=course_name_slug assessment_name_slug=assessment_name_slug  %}" enctype="multipart/form-data">
    {% csrf_token %}


    {{ assessment_grade_form.as_p }}
    {{ component_grade_formset.management_form }}

    {% for component_grade_form in component_grade_formset %}
    <div class="grade-formset">
      {% for field in component_grade_form %}
      {% if forloop.first %}
      {{field.value}}
      {% endif %}
      {% endfor %}
      
      {{ component_grade_form.as_p }}
    </div>
    {% endfor %}
    <br>

    <button class="btn btn-primary" type="submit">Save</button>
  </form>
</div>
{% endblock %}

templates/chemapp/edit_staff.html
{% extends 'chemapp/base.html' %}
{% load static %}

{% block js_block %}
<script src="{% static 'js/chemapp-courseInputMask.js' %}"></script>
{% endblock %}

{% block title_block %}
Edit a Staff Member
{% endblock %}

{% block body_block %}
<div class="container mb-5 ">
  <h2> Edit Staff </h2>

  <form id="edit_staff_form" method="post" action="{% url 'chemapp:edit_staff' staffID=staffID %}" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="row ">
      {% for field in edit_staff_form %}

      {% if field.label == 'First Name' %}
      <div class="col-4 mb-4">
        {% elif field.label == 'Last Name' %}
        <div class="col-4">
          {% elif field.label == 'Title' %}
          <div class="col-4">
            {% elif field.label == 'Comments' %}
            <div class="col-8">

              {% else %}
              <div class="col-12 mb-4">
                {% endif %}



                <div class="form-floating">
                  {{ field }}
                  <label for="floating{{ field.label }}">{{ field.label }}</label>
                </div>

                <div class=" text-start">
                  <div id="" class="form-text ps-2">{{ field.help_text }}</div>
                </div>



                {% for error in field.errors %}
                <div class="text-danger">
                  <strong>*{{ error|escape }}</strong>
                </div>
                {% endfor %}
              </div>


              {% endfor %}


              {% for error in form.non_field_errors %}
              <div class="">
                <strong>*{{ error|escape }}</strong>
              </div>
              {% endfor %}


            </div>

            <button class="btn btn-primary mt-5" type="submit">Save</button>
          </form>

        </div>

        {% endblock %}

templates/chemapp/search_course.html
{% extends 'chemapp/base.html' %}

{% block title_block %}
    Search Page
{% endblock %}

{% block body_block %}
<div class="container mt-5 ">
<h1>Search Page</h1>

<br/>



{% if submitbutton == 'Search' and request.GET.q != '' %}

<br><br>
<h1>Results for <b>{{ request.GET.q }}</b></h1>
<br/><br/>
<div class="col-3 d-grid gap-2 mt-3"  >
  <h2>Courses:</h2>
  {% for result in course_results %}
  <a class="btn text-start  pb-5" style="background-color:{{result.courseColor}}" href="{% url 'chemapp:course' course_name_slug=result.slug %}" role="button">
    <h2>{{ result.code }}</h2>
    {{ result.name }}
  </a>
{% endfor %}
<h2>Staff: </h2>
{% for result in staff_results %}
  <a href="{% url 'chemapp:staff_member' staffID=result.staffID %}">
    <button>{{result.title}} {{result.firstName}} {{result.lastName}}</button>
  </a>
{% endfor %}
<h2>Students: </h2>
{% for result in student_results %}
<a href="{% url 'chemapp:student' student_id=result.studentID %}">
  <button>{{result.firstName}} {{result.lastName}}</button>
</a>
{% endfor %}
</div>
{% endif %}
</div>
{% endblock %}